try {
    Promise.reject(1);
} catch (err) {
    console.log(1);
}
